### ISSUE TITLE
Failed to build with ffmpeg 6.1

### ISSUE THREAD

**Issue by linyinfeng** [LuckyTurtleDev/mstickereditor#41]
The dependency `ffmpeg-next` locked in Cargo.lock does not support FFmpeg 6.1, causing a build failure.

```
error[E0004]: non-exhaustive patterns: `sys::AVPixelFormat::AV_PIX_FMT_P212BE`, `sys::AVPixelFormat::AV_PIX_FMT_P212LE`, `sys::AVPixelFormat::AV_PIX_FMT_P412BE` and 3 more not covered
```

```toml
[[package]]
name = "ffmpeg-next"
version = "6.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8af03c47ad26832ab3aabc4cdbf210af3d3b878783edd5a7ba044ba33aab7a60"
dependencies = [
 "bitflags 1.3.2",
 "ffmpeg-sys-next",
 "libc",
]
```

Upstream of `ffmpeg-next` already fixed this issue in `https://github.com/zmwangx/rust-ffmpeg-sys/pull/65`, and released the fix on crates.io (https://crates.io/crates/ffmpeg-next/versions).

**Comment by bendschs** [comment]
same issue here with newly released version of msstickereditor
