### PR TITLE
Cargo update, fix bulid failure with ffmpeg 6.1, close #41

### LINKED ISSUE #41: Failed to build with ffmpeg 6.1
The dependency `ffmpeg-next` locked in Cargo.lock does not support FFmpeg 6.1, causing a build failure.

```
error[E0004]: non-exhaustive patterns: `sys::AVPixelFormat::AV_PIX_FMT_P212BE`, `sys::AVPixelFormat::AV_PIX_FMT_P212LE`, `sys::AVPixelFormat::AV_PIX_FMT_P412BE` and 3 more not covered
```

```toml
[[package]]
name = "ffmpeg-next"
version = "6.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8af03c47ad26832ab3aabc4cdbf210af3d3b878783edd5a7ba044ba33aab7a60"
dependencies = [
 "bitflags 1.3.2",
 "ffmpeg-sys-next",
 "libc",
]
```

Upstream of `ffmpeg-next` already fixed this issue in `https://github.com/zmwangx/rust-ffmpeg-sys/pull/65`, and released the fix on crates.io (https://crates.io/crates/ffmpeg-next/versions).

### PR DESCRIPTION
**Pull request by linyinfeng**
https://github.com/LuckyTurtleDev/mstickereditor/issues/41

### CODE REVIEW

**Review by msrd0 — APPROVED** [review]

**Comment by linyinfeng** [comment]
CI test fails <https://github.com/LuckyTurtleDev/mstickereditor/actions/runs/7553156702/job/20563757581?pr=42>. Seems `cargo update` raises new issues.
I'm going to convert this pull request to a draft.

**Comment by LuckyTurtleDev** [comment]
I was not able to reproduce the error local. So if have push the changes to an branch at this project and it works there. Apparently the pr do not have access to the projects secret, with cause the test to fail, because of missing bot token.

**Review by LuckyTurtleDev — APPROVED** [review]
